### ISSUE TITLE
Error when changing vote

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/riskmap-ng#15]
Server error when a user changes vote from upvote to downvote; or vice-versa,
Net points difference, -2 or +2
Server currently set to accept +1 or -1 as values. 

Ref:
https://github.com/urbanriskmap/riskmap-ng/blob/980ef346961a43c727c71d5fa004c67d665e6892/src/app/map/report-info/report-info.component.ts#L188

**Comment by talltom** [comment]
Can we make two -1 requests?
