### ISSUE TITLE
WhatsApp links aren't understood in Safari and Firefox

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/riskmap-ng#28]
Click the WhatsApp button on a desktop.

**Comment by ojha-url** [comment]
Seemed to be working for me, fixed error linked to #29
@talltom can you confirm and close?

**Comment by ojha-url** [comment]
Ref: https://webapps.stackexchange.com/questions/106145/whatsapp-link-with-phone-number-doesnt-open-whatsapps-web-app
- Works on chrome
- Works on iOS safari (iPhones)
- _Yet to check on Firefox_
- Doesn't work on MacOS safari (desktop)

Solution for now: 
- replace api.whatsapp.com with web.whatsapp.com if browser is safari and device is not mobile
- user will be asked to connect whatsapp web using QR code...
