### ISSUE TITLE
back button will not work/ takes repeated clicks

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/riskmap-ng#34]
back button will not work and create multiple notifications. Need to click it multiple times to actually go back.

**Comment by ojha-url** [comment]
Note to self:
Occurs when riskmap.us loads, and redirects to riskmap.us/broward
Back button takes you back to riskmap.us and then again redirects to riskmap.us/broward, creating a loop when back button is pressed repeatedly.

Will fix by clearing landing page without region param from the history on redirect.
