### ISSUE TITLE
Fix starting location for the map

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/riskmap-ng#35]
- GPS detected and is one of the instances - automatically load the map
- GPS is detected and not one of the instance regions - show city selector
- GPS is not detected and not one of the instance regions - show city selector

**Comment by ojha-url** [comment]
Not relevant for web-app, 
- user will either be directed via chatbots to website with region parameter filled in
- or if arriving through search / outreach, will be asked to select a region
