### ISSUE TITLE
Add pumps and flood gauges to map

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/riskmap-ng#7]
See: https://github.com/urbanriskmap/riskmap/issues/218

**Comment by ojha-url** [comment]
Added info pane, layer in dev-id environment:
86ce15738a842cf007aaeb9b2fc91b9aa30932bd

**Comment by ojha-url** [comment]
Closing as framework to add any layer is supported via environment.supportedLayers param. Pumps prototyped for jakarta deployment, gauges for broward.
