### ISSUE TITLE
Deployment dependent assets/ serving

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/riskmap-ng#8]
Use gulp task to copy deployment dependent assets from root folder to src/assets - pre-build task (test with travis)

**Comment by talltom** [comment]
@ojha-url Looks like this is already handled by .angular-cli.json.

Running `ng build --env=dev-us --output-path='dist/dev-us` copies the src/assets folder to dist/dev-us folder.

**Comment by ojha-url** [comment]
Created following task to serve deployment dependent assets and resources:
https://github.com/urbanriskmap/riskmap-ng/commit/2886ff0b5b67285ce89fbf0eee33b09bddb2864e#diff-20775e912f281e55670e7ab3446250e9

@talltom can you verify if the changes here: a261eebea3487942b6397bbf13f7d48fe2866d03 work with the travis project?

**Comment by talltom** [comment]
Okay, got it now. Closing this.
